### ISSUE TITLE
Laravel 8.x Support

### ISSUE THREAD

**Issue by chasebolt** [via-work/lever-php#35]
Any chance this could be bumped to work with Laravel 8.x?

**Comment by strotgen** [comment]
Hi Chase! We are not using L8 for this project, but I can release a new version for L8.

**Comment by strotgen** [comment]
I just released a version with Laravel 8 support. All tests are passing, but please test this yourself thoroughly as we are not using L8 ourselves.

**Comment by chasebolt** [comment]
any chance to get this bumped to php8 or php7.4? using laravel sail and that is the minimum supported versions.

**Comment by strotgen** [comment]
The composer version already allows for 7.4, but feel free to test it on PHP 8 and open PR to add support for it.

**Comment by chasebolt** [comment]
this is the issue im getting with PHP 7.4. a new install of laravel sets guzzle to 7.x.

```
$ ./vendor/bin/sail composer require via-work/lever-php 2.0.0

./composer.json has been updated
Running composer update via-work/lever-php
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires via-work/lever-php 2.0.0 -> satisfiable by via-work/lever-php[2.0.0].
    - via-work/lever-php 2.0.0 requires guzzlehttp/guzzle ^6.5 -> found guzzlehttp/guzzle[6.5.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.```

**Comment by strotgen** [comment]
Thank you for your PR. I already released a new version with your changes.
